version: '2'



  
volumes:
  prometheus_data: {}

networks:
  default:
    external:
        name: net_basic
        
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus-2.6.1/prometheus.yml:/home/best/Documents/Prometheus+Grafana/prometheus-2.6.1/prometheus.yml
    command:
      - '--config.file=/home/best/Documents/Prometheus+Grafana/prometheus-2.6.1/prometheus.yml'
    depends_on:
      - cadvisor
    ports:
      - '9090:9090'
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
      
  # fluentd_exporter:
  #   image: vect0r/fluentd_exporter
  #   ports:
  #     - '9309:9309'

  # elasticsearch_exporter:
  #   image: justwatch/elasticsearch_exporter:1.0.2
  #   command:
  #     - '-es.uri=http://elasticsearch:9200'
  #   restart: always
  #   ports:
  #     - "127.0.0.1:9108:9108"
    
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro




